development:
  host: localhost
  database: po_web_development

test:
  host: localhost
  database: po_web_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
